version: 0.1

phases:
  build:
    commands:
      - git ls-remote https://${GITHUB_TOKEN}@github.com/microservices-today/nginx-docker.git HEAD | awk '{ print $1;}' > master.commit
      - docker build -t $ECR_REPO:$(cat ./master.commit) .
      - sed -i "s@ECS_CLUSTER_NAME@${ECS_CLUSTER_NAME}@g" ecs/service.yaml
      - sed -i "s@TAG@$(cat ./master.commit)@g" ecs/service.yaml
      - sed -i "s@DOCKER_IMAGE_URI@$ECR_REPO:$(cat ./master.commit)@g" ecs/service.yaml
      
  post_build:
    commands:
      - docker images
      - export AWS_DEFAULT_REGION=$AWS_REGION
      - $(aws ecr get-login --region $AWS_REGION)
      - echo $ECR_REPO:$(cat ./master.commit)
      - docker push $ECR_REPO:$(cat ./master.commit)

artifacts:
  files:
    - task-definition.json
    - service-definition.json
    - ecs/service.yaml
    - master.commit
