AWSTemplateFormatVersion: "2010-09-09"

Description: >
  AWS CloudFormation Sample Template Continuous Delievery: This template
  builds an AWS CodePipeline pipeline that implements a continuous delivery release
  process for AWS CloudFormation stacks. Submit a CloudFormation source artifact
  to an Amazon S3 location before building the pipeline. The pipeline uses the
  artifact to automatically create stacks and change sets.
  **WARNING** This template creates Amazon EC2 instances. You will be billed
  for the AWS resources used when you create a stack using this template.

Parameters:
  PipelineName:
    Description: A name for pipeline
    Type: String
  GitHubRepo:
    Type: String
    Description: Github repo name (e.g. github.com/Org/RepoName then RepoName)
  GitHubBranch:
    Type: String
    Default: 'master'
    Description: The github branch to monitor for changes.
  GitHubToken:
    Type: String
    Description: The Github Token which has access to the repository.
  GitHubUser:
    Type: String
    Description: The Github User/Organisation under which the repository is hosted.
  Email:
    Description: The email address where CodePipeline sends pipeline notifications
    Type: String


Resources:
  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  CodePipelineSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref Email
          Protocol: email

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref 'ArtifactStoreBucket'
        Type: S3
      DisableInboundStageTransitions: []
      Name: !Ref 'PipelineName'
      RoleArn: !GetAtt [PipelineRole, Arn]
      Stages:
        - Name: S3Source
          Actions:
            - Name: TemplateSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                S3Bucket: !Ref 'S3Bucket'
                S3ObjectKey: !Ref 'SourceS3Key'
              OutputArtifacts:
                - Name: TemplateSource
              RunOrder: '1'
        - Name: DevEnvironment
          Actions:
            - Name: create-ECScluster
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Join ["-", ["Ref":"AWS::StackName", "Dev-ECSCluster"]]
                TemplatePath: TemplateSource::ecs-cluster.yaml
                TemplateConfiguration: TemplateSource::ecs-cluster-config.json
                ParameterOverrides: |
                  {
                    "EnvironmentName" : "DevEnvironment"
                  }
              RunOrder: '1'
            - Name: create-frontend-service
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Join ["-", ["Ref":"AWS::StackName", "DevFrontEndService"]]
                TemplatePath: TemplateSource::websiteservice.yaml
                TemplateConfiguration: TemplateSource::websiteservice-config.json
                ParameterOverrides: |
                  {
                    "EnvironmentName" : "DevEnvironment"
                  }
              RunOrder: '2'
            - Name: create-backend-service
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Join ["-", ["Ref":"AWS::StackName", "DevBackEndService"]]
                TemplatePath: TemplateSource::productservice.yaml
                TemplateConfiguration: TemplateSource::productservice-config.json
                ParameterOverrides: |
                  {
                    "EnvironmentName" : "DevEnvironment"
                  }
              RunOrder: '2'
        - Name: Cleanup-and-Promote
          Actions:
            - Name: ApproveCleanUp
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                NotificationArn: !Ref CodePipelineSNSTopic
                CustomData: 'Delete dev services and apply changes to prod?'
              RunOrder: '1'
            - Name: DeleteBackEnd
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: DELETE_ONLY
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Join ["-", ["Ref":"AWS::StackName", "DevBackEndService"]]
              RunOrder: '2'
            - Name: DeleteFrontEnd
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: DELETE_ONLY
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Join ["-", ["Ref":"AWS::StackName", "DevFrontEndService"]]
              RunOrder: '2'
            - Name: DeleteECScluster
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: DELETE_ONLY
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Join ["-", ["Ref":"AWS::StackName", "Dev-ECSCluster"]]
              RunOrder: '3'
        - Name: ProductionEnvironment
          Actions:
            - Name: Create-ECScluster-ChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Join ["-", ["Ref":"AWS::StackName", "Prod-ECSCluster"]]
                ChangeSetName: ChangesToProdECScluster
                TemplatePath: TemplateSource::ecs-cluster.yaml
                TemplateConfiguration: TemplateSource::ecs-cluster-config.json
                ParameterOverrides: |
                  {
                    "EnvironmentName" : "ProdEnvironment"
                  }
              RunOrder: '1'
            - Name: Create-FrontEnd-ChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Join ["-", ["Ref":"AWS::StackName", "ProdFrontEndService"]]
                ChangeSetName: ChangesToProdFrontEndSvc
                TemplatePath: TemplateSource::websiteservice.yaml
                TemplateConfiguration: TemplateSource::websiteservice-config.json
                ParameterOverrides: |
                  {
                    "EnvironmentName" : "ProdEnvironment"
                  }
              RunOrder: '1'
            - Name: Create-BackEnd-ChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: TemplateSource
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Join ["-", ["Ref":"AWS::StackName", "ProdBackEndService"]]
                ChangeSetName: ChangesToProdBackEndSvc
                TemplatePath: TemplateSource::productservice.yaml
                TemplateConfiguration: TemplateSource::productservice-config.json
                ParameterOverrides: |
                  {
                    "EnvironmentName" : "ProdEnvironment"
                  }
              RunOrder: '1'
            - Name: ApproveChangeSets
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                NotificationArn: !Ref CodePipelineSNSTopic
                CustomData: 'New change sets were created please review and approve if you want to implement the changes?'
              RunOrder: '2'
            - Name: Execute-ECScluster-ChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Join ["-", ["Ref":"AWS::StackName", "Prod-ECSCluster"]]
                ChangeSetName: ChangesToProdECScluster
              RunOrder: '3'
            - Name: Execute-FrontEnd-ChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Join ["-", ["Ref":"AWS::StackName", "ProdFrontEndService"]]
                ChangeSetName: ChangesToProdFrontEndSvc
              RunOrder: '4'
            - Name: Execute-BackEnd-ChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt [CFNRole, Arn]
                StackName: !Join ["-", ["Ref":"AWS::StackName", "ProdBackEndService"]]
                ChangeSetName: ChangesToProdBackEndSvc
              RunOrder: '4'

  CFNRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [cloudformation.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CloudFormationRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - '*'
                Effect: Allow
                Resource: '*'

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codepipeline.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 's3:*'
                - 'cloudformation:CreateStack'
                - 'cloudformation:DescribeStacks'
                - 'cloudformation:DeleteStack'
                - 'cloudformation:UpdateStack'
                - 'cloudformation:CreateChangeSet'
                - 'cloudformation:ExecuteChangeSet'
                - 'cloudformation:DeleteChangeSet'
                - 'cloudformation:DescribeChangeSet'
                - 'cloudformation:SetStackPolicy'
                - 'iam:PassRole'
                - 'sns:Publish'
                Effect: Allow
                Resource: '*'
