AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Tag:
    Type: String
    Description: Tag of the main part Docker Image.
    Default: TAG
  ECSClusterName:
    Type: String
    Description: Name of an existing ECS Cluster.
    Default: ECS_CLUSTER_NAME

Resources:
  Nginxtaskdefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Nginx-ng
      ContainerDefinitions:
      - Name: nginx
        Cpu: '10'
        Essential: 'true'
        Image:
          "Fn::Sub":
            - '145725228555.dkr.ecr.us-west-2.amazonaws.com/amal:TAG'
            - { AccountId: AWS::AccountId, Region: AWS::Region }
        Memory: '128'
        PortMappings:
        - ContainerPort: 80
          HostPort: 80
      Volumes:
      - Name: my-vol
  NginxService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: ECS_CLUSTER_NAME
      DesiredCount: '1'
      TaskDefinition:
        Ref: Nginxtaskdefinition
Outputs:
  ecsservice:
    Value:
      Ref: NginxService
