Description: >
    This template deploys an Application Load Balancer that exposes our various ECS services.
    We create them it a seperate nested template, so it can be referenced by all of the other nested templates.

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:

    LoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Name: !Ref EnvironmentName
            Subnets:
                - Fn::ImportValue: !Sub "${EnvironmentName}-PublicSubnet1"
                - Fn::ImportValue: !Sub "${EnvironmentName}-PublicSubnet2"
            SecurityGroups:
                - Fn::ImportValue: !Sub "${EnvironmentName}-LoadBalancerSecurityGroup"
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName

    LoadBalancerListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref LoadBalancer
            Port: 80
            Protocol: HTTP  
            DefaultActions:
                - Type: forward
                  TargetGroupArn: !Ref DefaultTargetGroup

    # We define a default target group here, as this is a mandatory Parameters
    # when creating an Application Load Balancer Listener. This is not used, instead
    # a target group is created per-service in each service template (../services/*)
    DefaultTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Name: !Ref EnvironmentName
            VpcId:
              Fn::ImportValue: !Sub "${EnvironmentName}-VPC"
            Port: 80
            Protocol: HTTP

Outputs:

    LoadBalancer:
        Description: A reference to the Application Load Balancer
        Value: !Ref LoadBalancer

    LoadBalancerUrl:
        Description: The URL of the ALB
        Value: !GetAtt LoadBalancer.DNSName
        Export:
            Name:  !Sub ${EnvironmentName}-DNSName

    Listener:
        Description: A reference to a port 80 listener
        Value: !Ref LoadBalancerListener
        Export:
            Name:  !Sub ${EnvironmentName}-Listener
